server:
  # 端口
  port: 8082
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议
    protocol: smtps
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: uuugzrgvnehabbgi
    # 发送者邮箱地址
    username: 903613657@qq.com
    # 端口（不同邮箱端口号不同）
    port: 465



  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: admin
    # 密码
    password: zx990416
    # 服务器地址
    host: 175.178.166.93
    # 端口
    port: 5673
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual

   #Redis配置
  redis:
    timeout: 10000ms                        # 连接超时时间
    host: 175.178.166.93                  # Redis服务器地址
    port: 6379                              # Redis服务器端口
    database: 0                             # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024                    # 最大连接数，默认 8
        max-wait: 10000ms                   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200                       # 最大空闲连接，默认 8
        min-idle: 5                          # 最小空闲连接，默认 0
